# Intro to Numpy
&copy; QuantSprout

Import the numpy package

In [2]:
import numpy as np

Make an array from a list.

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

Make an array from a list of lists

In [4]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

Make an array using a function.

In [5]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Make an array by starting at 0, incrementing by 2 and ending before 10

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Make an array of four evenly spaced numbers including both endpoints

In [8]:
np.linspace(0, 1, 4)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ])

Make an array of random numbers (using a normal distribution)

In [9]:
mean = 10
stdev = 3
number_values = 20
np.random.normal(mean, stdev, number_values)

array([ 10.11805691,   7.14266561,  11.02768201,  11.24823512,
        10.11426213,   9.68040193,  12.79392275,   5.43063406,
         7.08034595,  11.09525884,   9.25576774,   7.69043173,
        10.54739194,  11.53423709,   9.64892269,   9.46342769,
        10.13310746,  14.77314969,  11.94240237,   7.90221036])

#### Indexing Arrays
Access elements of a 1-dimensional array.  Get the first and last element

In [10]:
x = np.arange(4)
print x[0]
print x[-1]

0
3


Reshape an array

In [11]:
x = np.arange(6).reshape(2, 3)
print x

[[0 1 2]
 [3 4 5]]


Get the last row

In [12]:
print x[-1]     

[3 4 5]


Get the last element of the last row

In [13]:
print x[-1, -1]

5


Get elements like a list


In [14]:
x = np.arange(10) 
print x
print x[:3]
print x[1:4]
print x[-3:]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2 3]
[7 8 9]


Get all elements in reverse order

In [15]:
print x[::-1]

[9 8 7 6 5 4 3 2 1 0]


Get every second element or third element

In [16]:
print x[::2]
print x[::3]

[0 2 4 6 8]
[0 3 6 9]


In [17]:
x = np.arange(25).reshape(5, 5)
print x

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Get the first two columns and the first two rows

In [18]:
print x[:2, :2]   

[[0 1]
 [5 6]]


Get every second column of every second row

In [19]:
print x[::2, ::2] 

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


#### Access parts of an array with index arrays.

Generate six random integers between 0 and 9 inclusive

In [20]:
x = np.random.randint(0, 10, 6) 
print x

[5 8 3 7 0 6]


Get the first number and the last two numbers

In [21]:
indices = [0, -2, -1]
print x[indices]

[5 0 6]


Create two arrays

In [22]:
arrayLength = 5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1
print x1
print x2

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


Create a random shuffled range of numbers

In [23]:
indices = np.random.permutation(arrayLength)
print indices

[4 1 2 3 0]


Use indices to re-order arrays

In [24]:
print x1[indices]
print x2[indices]

[4 1 2 3 0]
[-4 -1 -2 -3  0]


Filter arrays by element value with boolean index arrays.

In [25]:
x = np.arange(5)
print x
print x > 2

[0 1 2 3 4]
[False False False  True  True]


In [26]:
print x[x > 2]
print x[np.array([False,False,False,True,True])]

[3 4]
[3 4]


Create 4 dimensional array

In [42]:
x = np.arange(16).reshape(2, 2, 2, 2)
print x

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


Index the array (try turning comments on/off)

In [46]:
# x
# print x[1]
# print x[0, 1]
# print x[0, 0, 0]
# print x[0, 0, 0, 0]
print x[1, 0, 1, 0]

10


#### Array Math
Try adding to a list

In [29]:
x = [1, 2, 3, 4]
# print x + 10

Try again with an array

In [30]:
x = np.array(x)
print x + 10

[11 12 13 14]


#### Flatten an Array
Create a 2 dimensional array

In [47]:
y = np.arange(9).reshape(3,3)
print y

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Use ravel to flatten the array

In [48]:
print y.ravel()

[0 1 2 3 4 5 6 7 8]


## Exercises

Create an array from 0 to 26 assign it to a variable x

In [49]:
x = np.arange(27)
print x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


Reverse the order of the array and re-assign it to x

In [50]:
x_reverse = x[::-1]
print x_reverse

[26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Convert the 1-dimensional array you created into a 3 dimensional array and re-assign it to x

In [51]:
x_3d  = x.reshape(3,3,3)
print x_3d

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Index only value 12

In [52]:
x_3d[1,1,0]

12

Convert x_3d back to a 1-dimensional array

In [53]:
x_3d.ravel()
# np.ravel(x_3d)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Create a random shuffled list of values from 0-19 and assign it to variable y

In [54]:
y = np.random.permutation(20)
print y

[15 16  6  1  8 19 12  5  4 17 18 13  7  2 11 14  3 10  0  9]


Create an array of boolean values for values in y that are greater than 10

In [55]:
y>10

array([ True,  True, False, False, False,  True,  True, False, False,
        True,  True,  True, False, False,  True,  True, False, False,
       False, False], dtype=bool)

Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

In [61]:
np.random.seed(0)
np.random.normal(10, 5, 20)

array([ 18.82026173,  12.00078604,  14.89368992,  21.204466  ,
        19.33778995,   5.1136106 ,  14.75044209,   9.24321396,
         9.48390574,  12.05299251,  10.72021786,  17.27136753,
        13.80518863,  10.60837508,  12.21931616,  11.66837164,
        17.47039537,   8.97420868,  11.56533851,   5.7295213 ])