# Python for Data Science Bootcamp
## Review Python, Numpy and Pandas
&copy; QuantSprout

Create a function that tests if a number is divisble by either 3 or 7 and returns either True or False

In [2]:
def divisible(x):
    if (x%3==0)|(x%7==0):
        result = True
    else:
        result = False
    return result

print divisible(7)
print divisible(12)
print divisible(13)

True
True
False


In [3]:
def divisible(x):
    return x%3==0 or x%7==0

print divisible(7)
print divisible(12)
print divisible(13)

True
True
False


Import Numpy and Pandas

In [4]:
import numpy as np
import pandas as pd

Create a 1-Dimensional Numpy Array with 8 Values from 0 to 7 and Assign it to a Variable x

In [5]:
x = np.arange(8)
print x

[0 1 2 3 4 5 6 7]


Reverse the Order of the Array

In [6]:
x_reverse = x[::-1]
print x_reverse

[7 6 5 4 3 2 1 0]


Reshape the Array into a 3-Dimensional Array

In [7]:
x_reshape = x.reshape(2,2,2)
print x_reshape

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


Import train.csv as a Pandas DataFrame

In [8]:
df = pd.read_csv('train.csv')

Investigate the DataFrame (e.g., Check first 5 rows of data, data types and review any summary statistics)

In [9]:
print df.head()
print df.info()
df.describe().T

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
<c

/Users/Craig_Sakuma/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42       NaN       NaN    NaN   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

What was the survival rate for men over the age of 50 in first class?

In [10]:
df['Survived'][(df.Sex=='male')&(df.Age>50)&(df.Pclass==1)].mean()

0.19230769230769232

Using groupby, calculate the average survival rate and age by both Sex and Pclass (Hint: use two columns for group by)

In [11]:
df.groupby(['Sex','Pclass'])['Survived','Age'].mean()

Survived        Age
Sex    Pclass                     
female 1       0.968085  34.611765
       2       0.921053  28.722973
       3       0.500000  21.750000
male   1       0.368852  41.281386
       2       0.157407  30.740707
       3       0.135447  26.507589

What are the names of the 10 oldest survivors?  (Hint: use sort)

In [17]:
survivors = df[df.Survived==1]
survivors.sort_values('Age',ascending=False, inplace=True)
survivors[['Name','Age']].iloc[:10]

/Users/Craig_Sakuma/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


Name   Age
630              Barkworth, Mr. Algernon Henry Wilson  80.0
275                 Andrews, Miss. Kornelia Theodosia  63.0
483                            Turkula, Mrs. (Hedwig)  63.0
829         Stone, Mrs. George Nelson (Martha Evelyn)  62.0
570                                Harris, Mr. George  62.0
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.0
587                  Frolicher-Stehli, Mr. Maxmillian  60.0
268     Graham, Mrs. William Thompson (Edith Junkins)  58.0
11                           Bonnell, Miss. Elizabeth  58.0
195                              Lurette, Miss. Elise  58.0

In [12]:
df[df.Survived==1].sort_values('Age',ascending=False)[['Name','Age']].iloc[:10]

Name   Age
630              Barkworth, Mr. Algernon Henry Wilson  80.0
275                 Andrews, Miss. Kornelia Theodosia  63.0
483                            Turkula, Mrs. (Hedwig)  63.0
829         Stone, Mrs. George Nelson (Martha Evelyn)  62.0
570                                Harris, Mr. George  62.0
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.0
587                  Frolicher-Stehli, Mr. Maxmillian  60.0
268     Graham, Mrs. William Thompson (Edith Junkins)  58.0
11                           Bonnell, Miss. Elizabeth  58.0
195                              Lurette, Miss. Elise  58.0