  # Python for Data Science Bootcamp
  ## K Nearest Neighbors

Import pandas and numpy packages

In [1]:
import numpy as np
import pandas as pd

Read the iris CSV file

In [2]:
iris = pd.read_csv('iris.csv')
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

Explore the data

In [3]:
iris.info()
iris.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null int64
dtypes: float64(4), int64(1)
memory usage: 5.9 KB


count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.054000  0.433594  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758667  1.764420  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.198667  0.763161  0.1  0.3  1.30  1.8  2.5
species       150.0  1.000000  0.819232  0.0  0.0  1.00  2.0  2.0

Create two variables for features and target.  Convert them into values.

In [4]:
iris_features = iris[['sepal_length','sepal_width',
                      'petal_length','petal_width']].values
iris_target = iris.species.values

Scikit-learn has a function to split data into training and testing sets

In [5]:
from sklearn.cross_validation import train_test_split

Apply train_test_split to sample data

In [29]:
example_features = [[1,10],[2,20],[3,30],[4,40],[5,50]]
example_target = ['a','b','c','d','e']

[f_train, f_test, t_train_, t_test] = \
    train_test_split (example_features, example_target, test_size=0.2,
                      random_state=0)

In [30]:
f_train

[[1, 10], [2, 20], [4, 40], [5, 50]]

In [31]:
f_test

[[3, 30]]

In [32]:
t_train

NameError: name 't_train' is not defined

In [33]:
t_test

['c']

View results of train_test_split 

In [22]:
print 'Training Set'
print f_train
print t_train
print '-----------------'
print 'Test Set'
print f_test
print t_test


Training Set
[[1, 10], [2, 20], [4, 40], [5, 50]]


NameError: name 't_train' is not defined

Split the iris data into training set and test set

In [14]:
features_train, features_test, target_train,\
    target_test = train_test_split(\
    iris_features, iris_target, test_size=0.20,\
    random_state=0)

In [147]:
features_test

array([[29.6991176471, True, 0.0, 0.0, 1.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [7.0, True, 0.0, 0.0, 1.0],
       [29.6991176471, False, 1.0, 0.0, 0.0],
       [29.0, False, 0.0, 0.0, 1.0],
       [29.6991176471, True, 1.0, 0.0, 0.0],
       [40.0, False, 1.0, 0.0, 0.0],
       [31.0, False, 1.0, 0.0, 0.0],
       [25.0, True, 1.0, 0.0, 0.0],
       [29.6991176471, False, 0.0, 0.0, 1.0],
       [26.0, True, 0.0, 0.0, 1.0],
       [40.0, False, 0.0, 1.0, 0.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [7.0, False, 0.0, 1.0, 0.0],
       [24.0, False, 1.0, 0.0, 0.0],
       [14.0, False, 0.0, 0.0, 1.0],
       [23.0, True, 0.0, 0.0, 1.0],
       [19.0, True, 0.0, 1.0, 0.0],
       [35.0, True, 0.0, 0.0, 1.0],
       [0.42, True, 0.0, 0.0, 1.0],
       [18.0, True, 0.0, 1.0, 0.0],
       [22.0, False, 1.0, 0.0, 0.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [29.6991176471, True, 1.0, 0.0, 0.0],
       [22.0, False, 0.0, 0.0, 1.0],
       [40.0, False

In [15]:
print features_train.shape
print features_test.shape
print target_train.shape
print target_test.shape


(120, 4)
(30, 4)
(120,)
(30,)


Import the K Nearest Neighbors classifier from scikit-learn

In [18]:
from sklearn.neighbors import KNeighborsClassifier

Train the KNN classifier

In [25]:
model = KNeighborsClassifier(5, weights='uniform').fit(features_train, target_train)

Compare predictions with actual results

In [26]:
print model.predict(features_test)
print target_test

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 2 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


Predict probabilities

In [27]:
model.predict_proba(features_test)

array([[ 0. ,  0. ,  1. ],
       [ 0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.2,  0.8],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.4,  0.6],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.8,  0.2],
       [ 0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.2,  0.8],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ]])

Score the model

In [28]:
model.score(features_test, target_test)

0.96666666666666667

## K-Folds Cross-Validation

Import the KFold function from scikit-learn

In [37]:
from sklearn.cross_validation import KFold

KFold function creates indices for separating training and test sets.  Lets create indices for a data set of 3 records with 3 folds.

In [58]:

k_fold_indices = KFold(3, n_folds=3, shuffle=False)
print k_fold_indices

print np.array(list(k_fold_indices))

sklearn.cross_validation.KFold(n=3, n_folds=3, shuffle=False, random_state=None)
[[array([1, 2]) array([0])]
 [array([0, 2]) array([1])]
 [array([0, 1]) array([2])]]


In [55]:
[[[1,2],[0]]]

[[[1, 2], [0]]]

Let's see what is in the k_fold_indices

In [59]:
k_fold_indices

sklearn.cross_validation.KFold(n=3, n_folds=3, shuffle=False, random_state=None)

In [60]:
for x,y in k_fold_indices:
    print x,y

[1 2] [0]
[0 2] [1]
[0 1] [2]


Remember how to index numpy arrays with indices?

In [61]:
sample = np.array([0,10,20,30,40,50])

indices = [4,0,2]
print sample[indices]

[40  0 20]


Let's use the indices to index values in an array.

In [62]:
data = np.array(['a','b','c'])
for x,y in k_fold_indices:
    print data[x],data[y]

['b' 'c'] ['a']
['a' 'c'] ['b']
['a' 'b'] ['c']


Function for calculating cross-validation

In [64]:
# cross validation function with average score
def cross_validate(features, target, classifier, k_fold, r_state=None) :

    # derive a set of (random) training and testing indices
    k_fold_indices = KFold(len(features), n_folds=k_fold,
                           shuffle=True, random_state=r_state)

    k_score_total = 0
    
    # for each training and testing slices run the classifier, and score the results
    for train_indices, test_indices in k_fold_indices :

        model = classifier.fit(features[train_indices],
                               target[train_indices])

        k_score = model.score(features[test_indices],
                              target[test_indices])

        k_score_total += k_score

    # return the average accuracy
    return k_score_total/k_fold

In [ ]:
# Better cross validation function with average score
def cross_validate2(features, k, weights, target, classifier, k_fold, r_state=None) :
#    model = KNeighborsClassifier(5).fit(titanic_features, titanic_target)
    # derive a set of (random) training and testing indices
    k_fold_indices = KFold(len(features), n_folds=k_fold,
                           shuffle=True, random_state=r_state)

    k_score_total = 0
    
    # for each training and testing slices run the classifier, and score the results
    for train_indices, test_indices in k_fold_indices :

        model = classifier.fit(features[train_indices],
                               target[train_indices])

        k_score = model.score(features[test_indices],
                              target[test_indices])

        k_score_total += k_score

    # return the average accuracy
    return k_score_total/k_fold

In [66]:
k_fold_indices = KFold(20,5, shuffle=True)

for train_indices, test_indices in k_fold_indices :
      print train_indices, ' - ',test_indices

[ 0  2  3  4  5  6  7  8  9 10 12 13 15 16 17 19]  -  [ 1 11 14 18]
[ 0  1  2  3  4  5  7  8 10 11 12 13 14 15 17 18]  -  [ 6  9 16 19]
[ 0  1  2  4  6  7  8  9 10 11 12 13 14 16 18 19]  -  [ 3  5 15 17]
[ 1  3  4  5  6  7  9 11 12 13 14 15 16 17 18 19]  -  [ 0  2  8 10]
[ 0  1  2  3  5  6  8  9 10 11 14 15 16 17 18 19]  -  [ 4  7 12 13]


Test the function with different numbers of neighbors

In [69]:
print 'Cross Validate with 3-fold : ' , cross_validate(iris_features, iris_target,
                    KNeighborsClassifier(3),10,0)
print '-----------------------------------------------'
print 'Cross Validate with 4-fold : ' , cross_validate(iris_features, iris_target,
                    KNeighborsClassifier(4),10,0)
print '-----------------------------------------------'
print 'Cross Validate with 5-fold : ' , cross_validate(iris_features, iris_target,
                    KNeighborsClassifier(5),10,0)


Cross Validate with 3-fold :  0.96
-----------------------------------------------
Cross Validate with 4-fold :  0.946666666667
-----------------------------------------------
Cross Validate with 5-fold :  0.96


## Exercise
####1. Load the clean_data.csv as a DataFrame

In [71]:
data=pd.read_csv('clean_data.csv', encoding='latin_1')

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
Unnamed: 0     891 non-null int64
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
_Pclass_1      891 non-null float64
_Pclass_2      891 non-null float64
_Pclass_3      891 non-null float64
dtypes: float64(5), int64(6), object(5)
memory usage: 111.4+ KB


In [72]:
data.head()

Unnamed: 0  PassengerId  Survived  Pclass  \
0           0            1         0       3   
1           1            2         1       1   
2           2            3         1       3   
3           3            4         1       1   
4           4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  _Pclass_1  _Pclass_2  \
0      0         A/5 21171   7.2500   NaN        S        0.0        0.0   
1      0          PC 17599  71.2833   C85        C        1.0        0.0   
2      0  STON/O2. 3101282   7.9250   NaN        S        0.0        0.0   
3      0            113803  53.1000  C123        S        1.0        0.0   
4      0            373450   8.0500   NaN        S        0.0        0.0   

   _Pclass_3  
0        1.0  
1        0.0  
2        1.0  
3        0.0  
4        1.0

In [92]:
data.Sex.replace(['male','female'],[True,False],inplace=True)

####2. Separate the data into features (limit to age, sex, pclass dummy variables) and target (Note: Make sure you convert the data to a numpy array by typing .values at end of DataFrame)

In [93]:
# convert as a numpy array !!!

titanic_features = data[['Age', 'Sex',  '_Pclass_1', '_Pclass_2','_Pclass_3']].values

titanic_target = data.Survived.values



In [94]:
print titanic_features

[[22.0 True 0.0 0.0 1.0]
 [38.0 False 1.0 0.0 0.0]
 [26.0 False 0.0 0.0 1.0]
 ..., 
 [29.6991176471 False 0.0 0.0 1.0]
 [26.0 True 1.0 0.0 0.0]
 [32.0 True 0.0 0.0 1.0]]


In [95]:
print titanic_target

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [96]:
 features_train, features_test, target_train, \
      target_test = train_test_split(
                titanic_features, titanic_target, test_size=0.20, random_state=0)
        
 print   '--- features_train ---'    
 print   features_train    
 print   '--- features_test ---'    
 print   features_test    
 print   '--- target_train ---'    
 print   target_train    
 print   '--- target_test ---'    
 print   target_test    



--- features_train ---
[[29.6991176471 False 0.0 0.0 1.0]
 [31.0 True 0.0 1.0 0.0]
 [31.0 True 0.0 1.0 0.0]
 ..., 
 [29.6991176471 True 0.0 0.0 1.0]
 [36.0 False 0.0 0.0 1.0]
 [60.0 True 0.0 1.0 0.0]]
--- features_test ---
[[29.6991176471 True 0.0 0.0 1.0]
 [29.6991176471 True 0.0 0.0 1.0]
 [7.0 True 0.0 0.0 1.0]
 [29.6991176471 False 1.0 0.0 0.0]
 [29.0 False 0.0 0.0 1.0]
 [29.6991176471 True 1.0 0.0 0.0]
 [40.0 False 1.0 0.0 0.0]
 [31.0 False 1.0 0.0 0.0]
 [25.0 True 1.0 0.0 0.0]
 [29.6991176471 False 0.0 0.0 1.0]
 [26.0 True 0.0 0.0 1.0]
 [40.0 False 0.0 1.0 0.0]
 [29.6991176471 True 0.0 0.0 1.0]
 [7.0 False 0.0 1.0 0.0]
 [24.0 False 1.0 0.0 0.0]
 [14.0 False 0.0 0.0 1.0]
 [23.0 True 0.0 0.0 1.0]
 [19.0 True 0.0 1.0 0.0]
 [35.0 True 0.0 0.0 1.0]
 [0.42 True 0.0 0.0 1.0]
 [18.0 True 0.0 1.0 0.0]
 [22.0 False 1.0 0.0 0.0]
 [29.6991176471 True 0.0 0.0 1.0]
 [29.6991176471 True 1.0 0.0 0.0]
 [22.0 False 0.0 0.0 1.0]
 [40.0 False 1.0 0.0 0.0]
 [32.0 True 0.0 0.0 1.0]
 [22.0 False 0.0 0.0

####3. Build a KNN model and test the accuracy of the model using kfold cross-validation

In [102]:
from sklearn.neighbors import KNeighborsClassifier

print "-----------------------------------"
model = KNeighborsClassifier(5,weights='uniform').fit(titanic_features, titanic_target)
print 'accuracy for 5 -fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 5, r_state=True)) 

print "-----------------------------------"
model = KNeighborsClassifier(5,weights='uniform').fit(titanic_features, titanic_target)
print 'accuracy for 5 -fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 5, r_state=True)) 

print "-----------------------------------"
model = KNeighborsClassifier(10,weights='uniform').fit(titanic_features, titanic_target)
print 'accuracy for 10-fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 10, r_state=True)) 

print "-----------------------------------"
model = KNeighborsClassifier(20,weights='uniform').fit(titanic_features, titanic_target)
print 'accuracy for 20-fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 20, r_state=True)) 

print "-----------------------------------"
model = KNeighborsClassifier(50).fit(titanic_features, titanic_target)
print 'accuracy for 50-fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 50, r_state=True)) 

print "-----------------------------------"
model = KNeighborsClassifier(100).fit(titanic_features, titanic_target)
print 'accuracy for 100-fold is : ' + str(cross_validate(titanic_features, titanic_target, model, 100, r_state=True)) 




-----------------------------------
accuracy for 5 -fold is : 0.767704475551
-----------------------------------
accuracy for 5 -fold is : 0.767704475551
-----------------------------------
accuracy for 10-fold is : 0.737403245943
-----------------------------------
accuracy for 20-fold is : 0.718434343434
-----------------------------------
accuracy for 50-fold is : 0.667254901961
-----------------------------------
accuracy for 100-fold is : 0.667083333333


### Bonus: Create a for loop to test different numbers of neighbors

In [109]:
from sklearn.neighbors import KNeighborsClassifier

for a in [3,5,10,15,20,50,100] :
    print "-----------------------------------"
    model = KNeighborsClassifier(a, weights='distance').fit(titanic_features, titanic_target)
    print 'accuracy for K='+str(a)+' for 10-fold is : ' + \
        str(cross_validate(titanic_features, titanic_target, model, 10, r_state=True)) 




-----------------------------------
accuracy for K=3 for 10-fold is : 0.776654182272
-----------------------------------
accuracy for K=5 for 10-fold is : 0.786766541823
-----------------------------------
accuracy for K=10 for 10-fold is : 0.796878901373
-----------------------------------
accuracy for K=15 for 10-fold is : 0.804731585518
-----------------------------------
accuracy for K=20 for 10-fold is : 0.789001248439
-----------------------------------
accuracy for K=50 for 10-fold is : 0.794606741573
-----------------------------------
accuracy for K=100 for 10-fold is : 0.795730337079


In [111]:
for a in range(1,120,5) :
    print "-----------------------------------"
    print 'accuracy for K='+str(a)+' for 10-fold is : ' + \
        str(cross_validate(titanic_features, titanic_target, KNeighborsClassifier(a, weights='distance'),\
                           10, r_state=True)) 
        #str(cross_validate(titanic_features, titanic_target, KNeighborsClassifier(a, weights='distance'),10,0)) 




-----------------------------------
accuracy for K=1 for 10-fold is : 0.751922596754
-----------------------------------
accuracy for K=6 for 10-fold is : 0.79013732834
-----------------------------------
accuracy for K=11 for 10-fold is : 0.80024968789
-----------------------------------
accuracy for K=16 for 10-fold is : 0.795742821473
-----------------------------------
accuracy for K=21 for 10-fold is : 0.792372034956
-----------------------------------
accuracy for K=26 for 10-fold is : 0.792372034956
-----------------------------------
accuracy for K=31 for 10-fold is : 0.795730337079
-----------------------------------
accuracy for K=36 for 10-fold is : 0.796853932584
-----------------------------------
accuracy for K=41 for 10-fold is : 0.799101123596
-----------------------------------
accuracy for K=46 for 10-fold is : 0.79797752809
-----------------------------------
accuracy for K=51 for 10-fold is : 0.793495630462
-----------------------------------
accuracy for K=56 for 1

##Data Normalization

Calculate the mean and standard deviation

In [112]:
avg_age = data.Age.mean()
stdev_age = data.Age.std()

Subtract the mean and divide by the standard deviation

In [116]:
data['Age_norm']= (
      data.Age - avg_age)/ stdev_age

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
Unnamed: 0     891 non-null int64
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null bool
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
_Pclass_1      891 non-null float64
_Pclass_2      891 non-null float64
_Pclass_3      891 non-null float64
Age_norm       891 non-null float64
dtypes: bool(1), float64(6), int64(6), object(4)
memory usage: 112.3+ KB


Create new features using normalized data

In [117]:
features_norm = data [['Age_norm','Sex','_Pclass_1','_Pclass_2','_Pclass_3']].values

Test KNN on normalized data

In [119]:
for k in range(1,10):
    model=KNeighborsClassifier(k)
    print cross_validate(features_norm,titanic_target,model,10,0)

0.762059925094
0.797952559301
0.790149812734
0.80138576779
0.796903870162
0.801360799001
0.802496878901
0.80024968789
0.799138576779


##Random Forest

Import the Random Forest function

In [120]:
from sklearn.ensemble import RandomForestClassifier

Create an instance of a random forest classifier.  Random state is used to set random number generator for reproducible results

In [121]:
model = RandomForestClassifier(random_state=0)

Run the cross-validation function using the Random Forest algorithm

In [123]:
for a in range(1,120,10) :
    print "-----------------------------------"
    print 'accuracy for K='+str(a)+' for 10-fold is : ' + \
        str(cross_validate(titanic_features, titanic_target, model,10, r_state=True)) 
        #str(cross_validate(titanic_features, titanic_target, KNeighborsClassifier(a, weights='distance'),10,0)) 



-----------------------------------
accuracy for K=1 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=11 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=21 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=31 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=41 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=51 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=61 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=71 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=81 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=91 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=101 for 10-fold is : 0.810312109863
-----------------------------------
accuracy for K=111

Investigate feature importances

In [124]:
print model.fit(titanic_features, titanic_target).feature_importances_

[ 0.4359133   0.40366222  0.05078753  0.02608483  0.08355212]


## Exercise

- Implement the random forest algorithm on the titanic data
- Review the random forest algorithm model parameters on sklearn 
- Adjust parameters to get the best model performance

### Make a Prediction for Kaggle

Train the model using the best data available (in the case of the Titanic you'd use all the data)

In [144]:
model = KNeighborsClassifier(5, weights='distance').fit(features_train, target_train)


Create a DataFrame with the test.csv data

In [220]:
df7 = pd.read_csv('test.csv')
df7.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [221]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [222]:
type(df7)

pandas.core.frame.DataFrame

In [223]:
df7.describe().T

count         mean         std     min     25%     50%      75%  \
PassengerId  418.0  1100.500000  120.810458  892.00  996.25  1100.5  1204.75   
Pclass       418.0     2.265550    0.841838    1.00    1.00     3.0     3.00   
Age          332.0    30.272590   14.181209    0.17     NaN     NaN      NaN   
SibSp        418.0     0.447368    0.896760    0.00    0.00     0.0     1.00   
Parch        418.0     0.392344    0.981429    0.00    0.00     0.0     0.00   
Fare         417.0    35.627188   55.907576    0.00     NaN     NaN      NaN   

                   max  
PassengerId  1309.0000  
Pclass          3.0000  
Age            76.0000  
SibSp           8.0000  
Parch           9.0000  
Fare          512.3292

Clean text and missing values

In [224]:
df7.Sex.replace(['male','female'],[True,False],inplace=True)

In [225]:
avg_Age = df7.Age.mean()
print avg_Age

30.2725903614


In [228]:
df7.Age.fillna(avg_Age, inplace=True)

In [231]:
#df7_ = df7.dropna(subset=['Sex','Age','Pclass'])
df7.describe().T

count         mean         std     min     25%         50%  \
PassengerId  418.0  1100.500000  120.810458  892.00  996.25  1100.50000   
Pclass       418.0     2.265550    0.841838    1.00    1.00     3.00000   
Age          418.0    30.272590   12.634534    0.17   23.00    30.27259   
SibSp        418.0     0.447368    0.896760    0.00    0.00     0.00000   
Parch        418.0     0.392344    0.981429    0.00    0.00     0.00000   
Fare         417.0    35.627188   55.907576    0.00     NaN         NaN   

                 75%        max  
PassengerId  1204.75  1309.0000  
Pclass          3.00     3.0000  
Age            35.75    76.0000  
SibSp           1.00     8.0000  
Parch           0.00     9.0000  
Fare             NaN   512.3292

In [232]:
df7.Sex.value_counts()

True     266
False    152
Name: Sex, dtype: int64

In [233]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null bool
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 33.1+ KB


In [234]:
df7.Pclass.value_counts()

3    218
1    107
2     93
Name: Pclass, dtype: int64

Convert Pclass to dummies and merge to data

In [235]:
df7_1 = pd.get_dummies(df7.Pclass, prefix='_Pclass')
df7_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 3 columns):
_Pclass_1    418 non-null float64
_Pclass_2    418 non-null float64
_Pclass_3    418 non-null float64
dtypes: float64(3)
memory usage: 9.9 KB


In [236]:
df = pd.merge(df7, df7_1, left_index=True, right_index=True)
df.info()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 14 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null bool
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
_Pclass_1      418 non-null float64
_Pclass_2      418 non-null float64
_Pclass_3      418 non-null float64
dtypes: bool(1), float64(5), int64(4), object(4)
memory usage: 42.9+ KB


count         mean         std     min     25%         50%  \
PassengerId  418.0  1100.500000  120.810458  892.00  996.25  1100.50000   
Pclass       418.0     2.265550    0.841838    1.00    1.00     3.00000   
Age          418.0    30.272590   12.634534    0.17   23.00    30.27259   
SibSp        418.0     0.447368    0.896760    0.00    0.00     0.00000   
Parch        418.0     0.392344    0.981429    0.00    0.00     0.00000   
Fare         417.0    35.627188   55.907576    0.00     NaN         NaN   
_Pclass_1    418.0     0.255981    0.436934    0.00    0.00     0.00000   
_Pclass_2    418.0     0.222488    0.416416    0.00    0.00     0.00000   
_Pclass_3    418.0     0.521531    0.500135    0.00    0.00     1.00000   

                 75%        max  
PassengerId  1204.75  1309.0000  
Pclass          3.00     3.0000  
Age            35.75    76.0000  
SibSp           1.00     8.0000  
Parch           0.00     9.0000  
Fare             NaN   512.3292  
_Pclass_1       1.00     1.0000  
_Pclass_2       0.00     1.0000  
_Pclass_3       1.00     1.0000

Select features from test data and convert to numpy array

In [237]:
titanic_features2 = df[['Age', 'Sex',  '_Pclass_1', '_Pclass_2','_Pclass_3']].values

#titanic_target2 = data.Survived.values
titanic_features2

array([[34.5, True, 0.0, 0.0, 1.0],
       [47.0, False, 0.0, 0.0, 1.0],
       [62.0, True, 0.0, 1.0, 0.0],
       ..., 
       [38.5, True, 0.0, 0.0, 1.0],
       [30.272590361445783, True, 0.0, 0.0, 1.0],
       [30.272590361445783, True, 0.0, 0.0, 1.0]], dtype=object)

In [179]:
#print model.predict(features_test)
features_test #previous example !!

array([[29.6991176471, True, 0.0, 0.0, 1.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [7.0, True, 0.0, 0.0, 1.0],
       [29.6991176471, False, 1.0, 0.0, 0.0],
       [29.0, False, 0.0, 0.0, 1.0],
       [29.6991176471, True, 1.0, 0.0, 0.0],
       [40.0, False, 1.0, 0.0, 0.0],
       [31.0, False, 1.0, 0.0, 0.0],
       [25.0, True, 1.0, 0.0, 0.0],
       [29.6991176471, False, 0.0, 0.0, 1.0],
       [26.0, True, 0.0, 0.0, 1.0],
       [40.0, False, 0.0, 1.0, 0.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [7.0, False, 0.0, 1.0, 0.0],
       [24.0, False, 1.0, 0.0, 0.0],
       [14.0, False, 0.0, 0.0, 1.0],
       [23.0, True, 0.0, 0.0, 1.0],
       [19.0, True, 0.0, 1.0, 0.0],
       [35.0, True, 0.0, 0.0, 1.0],
       [0.42, True, 0.0, 0.0, 1.0],
       [18.0, True, 0.0, 1.0, 0.0],
       [22.0, False, 1.0, 0.0, 0.0],
       [29.6991176471, True, 0.0, 0.0, 1.0],
       [29.6991176471, True, 1.0, 0.0, 0.0],
       [22.0, False, 0.0, 0.0, 1.0],
       [40.0, False

Create predictions

In [238]:
#model.predict(titanic_features2)
my_prediction = model.predict(titanic_features2)
my_prediction

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0,

Add Predictions as new column in DataFrame

In [239]:
df

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [240]:
dfp = pd.DataFrame(my_prediction)
dfp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 1 columns):
0    418 non-null int64
dtypes: int64(1)
memory usage: 3.3 KB


In [241]:
dfp.describe().T

count      mean       std  min  25%  50%  75%  max
0  418.0  0.308612  0.462474  0.0  0.0  0.0  1.0  1.0

In [242]:
df_ok = pd.merge(df, dfp, left_index=True, right_index=True)
df_ok.head()
df_ok.rename(columns={0:'Survived'},inplace=True)
df_ok.describe().T
df_ok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 15 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null bool
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
_Pclass_1      418 non-null float64
_Pclass_2      418 non-null float64
_Pclass_3      418 non-null float64
Survived       418 non-null int64
dtypes: bool(1), float64(5), int64(5), object(4)
memory usage: 46.2+ KB


In [254]:
df_ok['Survived'].value_counts()

0    289
1    129
Name: Survived, dtype: int64

Save as CSV (make sure you set index=False)

Save as CSV (make sure you set index=False)

In [260]:
df_final = df_ok[['PassengerId','Survived']]

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
PassengerId    418 non-null int64
Survived       418 non-null int64
dtypes: int64(2)
memory usage: 6.6 KB


In [261]:
df_final.describe().T

count         mean         std    min     25%     50%      75%  \
PassengerId  418.0  1100.500000  120.810458  892.0  996.25  1100.5  1204.75   
Survived     418.0     0.308612    0.462474    0.0    0.00     0.0     1.00   

                max  
PassengerId  1309.0  
Survived        1.0

In [264]:
df_final.to_csv('prediction_result.csv', header=True, index=False)

In [265]:
my_result = pd.read_csv('prediction_result.csv')
my_result.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         1
4          896         1