# Python for Data Science Bootcamp
## Intro to Numpy
&copy; QuantSprout

Import the numpy package

In [1]:
import numpy as np

Make an array from a list.

In [3]:
np.array([1,2,3])

array([1, 2, 3])

Make an array from a list of lists

In [18]:
y = np.array([[1,2],[3,4,5,6], [23,9,11]])  # like a matrix (two dimensional array)
print y 
print y [1]
print y [0]
print y [2]
print "-------------------"
print len(y)
print y.shape
print y.dtype

[[1, 2] [3, 4, 5, 6] [23, 9, 11]]
[3, 4, 5, 6]
[1, 2]
[23, 9, 11]
-------------------
3
(3,)
object


In [12]:
x = np.array([[1,2],[3,4]])  # like a matrix (two dimensional array)
print x 
x.shape

[[1 2]
 [3 4]]


(2, 2)

In [16]:
x1 = np.array([1,2])
print x1.shape
print x1.dtype

(2,)
int64


In [14]:
z = np.array ([[1,2,None],[2,4,5]])
print z
z.shape

[[1 2 None]
 [2 4 5]]


(2, 3)

Make an array using a function.

In [24]:
a1 = np.zeros([2,3])
print a1
a2 = np.zeros((2,3))
print a2


[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
b = np.ones((3,2))
print b
print len(b)
print b.shape

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
3
(3, 2)


In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Make an array by starting at 0, incrementing by 2 and ending before 10

In [137]:
np.arange(0,10,2)

Make an array of four evenly spaced numbers including both endpoints

In [26]:
np.linspace (0,1,4)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ])

Make an array of random numbers (using a normal distribution)

In [28]:
mean = 10
stdev = 3
number_values = 20
np.random.normal (mean, stedev. number_values)

AttributeError: 'int' object has no attribute 'number_values'

#### Indexing Arrays
Access elements of a 1-dimensional array.  Get the first and last element

In [33]:
x = np.arange(4)
print x[0]
print x[-1]

0
3


Reshape an array

In [34]:
x = np.arange(6).reshape(2,3)
print x

[[0 1 2]
 [3 4 5]]


In [35]:
x = np.arange(6).reshape(3,2)
print x

[[0 1]
 [2 3]
 [4 5]]


Get the last row

In [36]:
print x[-1]

[4 5]


In [39]:
print x[0, -1]  #--- like an (x,y) coordinates

1


In [40]:
print x[-1, -1]

5


In [42]:
print x[:3]

[[0 1]
 [2 3]
 [4 5]]


In [43]:
print x[0:]

[[0 1]
 [2 3]
 [4 5]]


In [44]:
print x [1:4]

[[2 3]
 [4 5]]


Get the last element of the last row

In [38]:
print x[2,1]

5


Get elements like a list


Get all elements in reverse order

Get every second element or third element

Create a 5x5 matrix

In [48]:
x = np.arange(40)
print x
y = x.reshape(5,8)
print y
z = x.reshape(8,5)
print z
a = x.reshape(2,2,10)
print a


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]


In [51]:
x = np.arange(25).reshape(5,5)
print x

print "------ x[:2, :2] is : ---------- pick a value inside a range with every step of 2------"
print x[:2, :2]

print "------ x[::2, ::2] is : ----------------"
print x[::2, ::2]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------ x[:2, :2] is : ----------------
[[0 1]
 [5 6]]
------ x[::2, ::2] is : ----------------
[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


Get the first two columns and the first two rows

In [138]:
x[:2, :2]

Get every second column of every second row

In [138]:
x[::2, ::2]

#### Access parts of an array with index arrays.

Generate six random integers between 0 and 9 inclusive

In [55]:
xx1 = np.random.randint(0,10,6)
print xx1

[2 1 5 0 0 1]


In [58]:
xx2 = np.random.randint(0,20,6)
print xx2

[10  8 19 13  5 17]


In [63]:
xx3 = np.random.randint(0,20,20)
print xx3

[16 19 15 18  0  5 11 18  6 14 14  9 10  9 11 14 13  7  0 12]


In [71]:
xx4 = range(0,10,1)
print xx4

xx5 = np.array(xx4)
print xx5

xx6 = np.arange(10)                # generate an ordered list
print xx6

xx7 = np.random.permutation(xx6)   # shuffle the range of number with random order
print xx7

xx8 = np.random.permutation(7)   # shuffle the range of number with random order
print xx8

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[7 0 9 5 8 1 6 4 3 2]
[0 5 6 4 2 3 1]


Get the first number and the last two numbers

In [59]:
indices = [0,-2,-1]
print x[indices]

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Create two arrays

In [73]:
arrayLength =5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1
print x1
print x2

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


Create a random shuffled range of numbers

In [138]:
xx7 = np.random.permutation(xx6)   # shuffle the range of number with random order
print xx7

Use indices to re-order arrays

Create array of boolean values

In [76]:
x = np.arange(5)
print x
print x > 2
print x + 1
print x **2

[0 1 2 3 4]
[False False False  True  True]
[1 2 3 4 5]
[ 0  1  4  9 16]


Use boolean values to index arrays

In [82]:
print x [x>2]



[3 4]


In [83]:
print x[np.array([False, False, False, True,True])]



[3 4]


Create 4 dimensional array

In [85]:
xy = np.arange(16).reshape (2,2,2,2)
print xy

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


Index the array (try turning comments on/off)

In [86]:
print xy

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [88]:
print xy[1,1,1,1]

15


In [91]:
print xy[1]

[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [92]:
print xy [0,1]

[[4 5]
 [6 7]]


In [93]:
print xy [0,0,0]

[0 1]


In [94]:
print xy [0,0,0,1]

1


In [95]:
print xy [0,0,1,0]

2


In [97]:
print xy [0,1]

[[4 5]
 [6 7]]


In [98]:
print xy [0,1,0]

[4 5]


#### Array Math
Try adding to a list

Try again with an array

In [99]:
x = [1,2,3,4]
print x + 10

TypeError: can only concatenate list (not "int") to list

In [100]:
x = np.array([1,2,3,4])
print x + 10

[11 12 13 14]


#### Flatten an Array
Create a 2 dimensional array

In [103]:
zy = np.arange(9).reshape(3,3)
print zy

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Use ravel to flatten the array

In [104]:
zz=zy.ravel()
print zz

[0 1 2 3 4 5 6 7 8]


## Exercise

Create an array from 0 to 26 assign it to a variable x

In [111]:
x = np.arange(27)
print x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


Reverse the order of the array and re-assign it to x_reverse

In [112]:
y = x[::-1]
print y

[26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Convert the 1-dimensional array you created into a 3 dimensional array and re-assign it to x_3d

In [114]:
x_3d =y.reshape(3,3,3)
print x_3d

[[[26 25 24]
  [23 22 21]
  [20 19 18]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]


Index only value 12

In [119]:
print x_3d[1,1,2]
print x_3d[-2,-2,-1]

12
12


Convert x_3d back to a 1 dimensional array

In [138]:
x_1d = x_3d.ravel()
print x_1d

In [128]:
print x_1d
indices = np.random.permutation (x_1d)
print x_1d [indices]

[26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
[ 7  2  5 20 17 12 19 14  6 10  4 15  8 24 11 13 16 21  0  3 25 18 26  1  9
 22 23]


Create a random shuffled list of values from 0-19 and assign it to variable y

In [129]:
y = np.random.permutation (20)
print y

[15 12 18  8 17 13  0  7  9 16  3 11 14  2  6  1 10  4  5 19]


Create an array of boolean values for values in y that are greater than 10

In [127]:
z = x_1d > 10
print z

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False]


Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

In [130]:
 s = np.random.randint(0,100,20)
 print s   

[79 39 19 39 14 16 95 14 59 44 58 99 93 99 10 84 64 72 93 37]


In [131]:
mean = 10
sd = 5
number_values = 20
np.random.normal(mean, sd,number_values)

array([ -5.98616743,  14.25094323,   5.39212201,   7.22571107,
        24.87315339,   4.87610991,   8.16295039,  12.77766931,
         7.48262773,   1.82842222,   6.39810685,   7.67720084,
        11.52995384,  13.9308923 ,   7.30623252,  13.74707477,
         6.36423927,  10.2676449 ,   9.19043981,  10.09638984])

In [134]:
np.random.seed(0)   # it will make your random result the same every time
np.random.normal(10,5,20)

array([ 18.82026173,  12.00078604,  14.89368992,  21.204466  ,
        19.33778995,   5.1136106 ,  14.75044209,   9.24321396,
         9.48390574,  12.05299251,  10.72021786,  17.27136753,
        13.80518863,  10.60837508,  12.21931616,  11.66837164,
        17.47039537,   8.97420868,  11.56533851,   5.7295213 ])