# Python for Data Science Bootcamp
## Review Python, Numpy and Pandas
&copy; QuantSprout

Create a function that tests if a number is divisble by either 3 or 7 and returns either True or False

In [6]:
def check_divisible (a_number):
    
    if type(a_number)<> int :
        return "Wrong data type! Please input an integer"
    else:
        if (a_number % 3)==0 or (a_number % 7)==0 :
            return "True"
        else :
            return "False"
    
print 'check_divisible (3) is : ' + check_divisible (3) 
print 'check_divisible (7) is : ' + check_divisible (7) 
print 'check_divisible (4) is : ' + check_divisible (4) 
print 'check_divisible (3) is : ' + check_divisible (3) 
print 'check_divisible (-9) is : ' + check_divisible (-9) 
print 'check_divisible ("jdgs") is : ' + check_divisible ('jdgs') 




check_divisible (3) is : True
check_divisible (7) is : True
check_divisible (4) is : False
check_divisible (3) is : True
check_divisible (-9) is : True
check_divisible ("jdgs") is : Wrong data type! Please input an integer


Import Numpy and Pandas

In [7]:
import numpy as np
import pandas as pd

Create a 1-Dimensional Numpy Array with 8 Values from 0 to 7 and Assign it to a Variable x

In [30]:
x0 = np.arange(8)
print x0

x = np.arange(0,8,1)
print x

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


Reverse the Order of the Array

In [13]:
print x[::-1]
y = x[::-1]

[7 6 5 4 3 2 1 0]


Reshape the Array into a 3-Dimensional Array

In [31]:
z = y.reshape(2,4)
print z

a = y.reshape(2,2,2)
print a

[[7 6 5 4]
 [3 2 1 0]]
[[[7 6]
  [5 4]]

 [[3 2]
  [1 0]]]


Import train.csv as a Pandas DataFrame

In [38]:
df = pd.read_csv('train.csv', header=None)

Investigate the DataFrame (e.g., Check first 5 rows of data, data types and review any summary statistics)

In [39]:
df.head(5)
df.head()

0         1       2   \
0  PassengerId  Survived  Pclass   
1            1         0       3   
2            2         1       1   
3            3         1       3   
4            4         1       1   

                                                  3       4    5      6   \
0                                               Name     Sex  Age  SibSp   
1                            Braund, Mr. Owen Harris    male   22      1   
2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
3                             Heikkinen, Miss. Laina  female   26      0   
4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   

      7                 8        9      10        11  
0  Parch            Ticket     Fare  Cabin  Embarked  
1      0         A/5 21171     7.25    NaN         S  
2      0          PC 17599  71.2833    C85         C  
3      0  STON/O2. 3101282    7.925    NaN         S  
4      0            113803     53.1   C123         S

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
0     892 non-null object
1     892 non-null object
2     892 non-null object
3     892 non-null object
4     892 non-null object
5     715 non-null object
6     892 non-null object
7     892 non-null object
8     892 non-null object
9     892 non-null object
10    205 non-null object
11    890 non-null object
dtypes: object(12)
memory usage: 83.7+ KB


In [41]:
df.describe()



0    1    2                          3     4    5    6    7       8   \
count   892  892  892                        892   892  715  892  892     892   
unique  892    3    4                        892     3   89    8    8     682   
top     823    0    3  Graham, Mr. George Edward  male   24    0    0  347082   
freq      1  549  491                          1   577   30  608  678       7   

          9            10   11  
count    892          205  890  
unique   249          148    4  
top     8.05  C23 C25 C27    S  
freq      43            4  644

In [42]:
df.describe().T

count unique                        top freq
0    892    892                        823    1
1    892      3                          0  549
2    892      4                          3  491
3    892    892  Graham, Mr. George Edward    1
4    892      3                       male  577
5    715     89                         24   30
6    892      8                          0  608
7    892      8                          0  678
8    892    682                     347082    7
9    892    249                       8.05   43
10   205    148                C23 C25 C27    4
11   890      4                          S  644

In [43]:
df.tail(5)

0  1  2                                         3       4    5  6  7   \
887  887  0  2                     Montvila, Rev. Juozas    male   27  0  0   
888  888  1  1              Graham, Miss. Margaret Edith  female   19  0  0   
889  889  0  3  Johnston, Miss. Catherine Helen "Carrie"  female  NaN  1  2   
890  890  1  1                     Behr, Mr. Karl Howell    male   26  0  0   
891  891  0  3                       Dooley, Mr. Patrick    male   32  0  0   

             8      9     10 11  
887      211536     13   NaN  S  
888      112053     30   B42  S  
889  W./C. 6607  23.45   NaN  S  
890      111369     30  C148  C  
891      370376   7.75   NaN  Q

What was the survival rate for men over the age of 50 in first class?

In [52]:
df['Age']

KeyError: 'Age'

In [49]:
df['Survived'][(df.Sex=='male') & (df.Age > 50) & (df.Pclass == 1)].mean()

KeyError: 'Survived'

Using groupby, calculate the average survival rate and age by both Sex and Pclass (Hint: use two columns for group by)

In [37]:
df.groupby(['Sex','Pclass'])['Survived','Age'].mean()

KeyError: 'Sex'

Who are the 10 oldest survivors?  (Hint: use sort)

In [47]:
survivors = df[df.Survived ==1]
survivors.sort_values(['Age','Sex'],ascending=False,inplace =True)
survivors[['Name','Age']].iloc[:10]


AttributeError: 'DataFrame' object has no attribute 'Survived'

In [46]:
survivors = df[df.Survived ==1].sort_values(['Age','Sex'],ascending=False,inplace =True)[['Name','Age']].iloc[:10]

AttributeError: 'DataFrame' object has no attribute 'Survived'

In [ ]:
df.sort